<%@ Page Title="RawList" Language="C#" MasterPageFile="~/Site.Master" CodeBehind="Default.aspx.cs" Inherits="FrontierAg.Admin.Raws.Default" %>

<%@ Register TagPrefix="FriendlyUrls" Namespace="Microsoft.AspNet.FriendlyUrls" %>
<asp:Content runat="server" ContentPlaceHolderID="MainContent">    
    <script type="text/javascript">        
        $(function () {                                    
            $('span:contains("AG_")').each(function () {
                $(this).html($('span:contains("AG_")').html().replace("AG_", ""));
            });
            $('td:contains("12:00:00 AM")').each(function () {
                $(this).html($('td:contains("12:00:00 AM")').html().replace("12:00:00 AM", ""));
            });
        });
    </script>
    <div class="PrintHidden2">
        <h3>Raw Materials</h3>
        <p>
            <asp:HyperLink runat="server" NavigateUrl="Insert" Text="Create new" />
        
        <asp:TextBox ID="TextBox1" runat="server" CssClass="form-control" AutoPostBack="True" EnableViewState="False" OnTextChanged="TextBox1_TextChanged" placeholder="Search or SPACE to RESET" Width="300px"></asp:TextBox>
        </p>
            <asp:GridView runat="server" ID="RawsGrid" CssClass="table table-striped table-bordered"
            ItemType="FrontierAg.Models.Raw" DataKeyNames="RawId" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            SelectMethod="GetData3" UpdateMethod="RawsGrid_UpdateItem" DeleteMethod="RawsGrid_DeleteItem"
            AutoGenerateColumns="false" AllowSorting="true" AllowPaging="true" PageSize="35">
            <Columns>
                <asp:DynamicField DataField="DateRecived" />
                <asp:TemplateField HeaderText="Description">
                    <ItemTemplate>
                        <asp:Label Text="<%#:Item.Product.ProductName %>"
                            runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:DynamicField DataField="Manufacturer" />
                <asp:DynamicField DataField="ManPartNumber" />
                <asp:DynamicField DataField="ManLotNumber" />
                <asp:TemplateField HeaderText="Frontier Product#">
                    <ItemTemplate>
                        <asp:Label Text="<%#:Item.Product.ProductNo %>"
                            runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:DynamicField DataField="LotNumber" ReadOnly="true"/>                               
                <asp:DynamicField DataField="ExpDate" />                
                <asp:HyperLinkField Text="Print Label" DataNavigateUrlFormatString="~/Admin/Raws/Details/{0}" DataNavigateUrlFields="RawId" />
            </Columns>
        </asp:GridView>
        <div class="row">
            &nbsp;
        </div>
        <div class="form-group">
            <div>
                <asp:Button ID="backButton" runat="server" Text="Back" OnClientClick="JavaScript:window.history.back(1);return false;" CssClass="btn btn-warning" />
            </div>
        </div>
    </div>

</asp:Content>

