<%@ Page Title="RawList" Language="C#" MasterPageFile="~/Site.Master" CodeBehind="Default.aspx.cs" Inherits="FrontierAg.Admin.Raws.Default" %>  

<%@ Register TagPrefix="FriendlyUrls" Namespace="Microsoft.AspNet.FriendlyUrls" %>
<asp:Content runat="server" ContentPlaceHolderID="MainContent">   
    
    <script type="text/javascript">        
        $(function () {
            if ($('span:contains("AG_")').length)
            {
                $('span:contains("AG_")').html($('span:contains("AG_")').html().replace("AG_", ""));
            }                                       
        });
    </script>
    <div>
        <h3>Raw Material List</h3>
        <p>
            <asp:HyperLink runat="server" NavigateUrl="Insert" Text="Create new" />           
        </p>
                 
        <asp:TextBox ID="TextBox1" runat="server" CssClass="form-control" AutoPostBack="true" placeholder="Search by Description"  OnTextChanged="TextBox1_TextChanged" ></asp:TextBox>
        <br />
        <asp:GridView runat="server" ID="RawsGrid" CssClass="table table-striped table-bordered"
            ItemType="FrontierAg.Models.Raw" DataKeyNames="RawId" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
            SelectMethod="GetData" UpdateMethod="RawsGrid_UpdateItem" DeleteMethod="RawsGrid_DeleteItem"
            AutoGenerateColumns="false">
            <Columns>
                <asp:DynamicField DataField="DateRecived" />
                <asp:TemplateField HeaderText="Description">
                    <ItemTemplate>
                        <asp:Label Text="<%# Item.Product.ProductName %>"
                            runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:DynamicField DataField="Manufacturer" />
                <asp:DynamicField DataField="ManPartNumber" />
                <asp:DynamicField DataField="ManLotNumber" />
                <asp:TemplateField HeaderText="Frontier Product#">
                    <ItemTemplate>
                        <asp:Label Text="<%# Item.Product.ProductNo %>"
                            runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:DynamicField DataField="LotNumber" ReadOnly="true"/>
                <asp:DynamicField DataField="ExpDate" />
                <%--<asp:ButtonField ButtonType="Link" Text="Print Label" ControlStyle-CssClass="test1" />--%>
                <asp:HyperLinkField Text="Print Label" DataNavigateUrlFormatString="~/Admin/Raws/Details/{0}" DataNavigateUrlFields="RawId" />
            </Columns>
        </asp:GridView>
        <div class="row">
            &nbsp;
        </div>
        <div class="form-group">
            <div>
                <asp:Button ID="backButton" runat="server" Text="Back" OnClientClick="JavaScript:window.history.back(1);return false;" CssClass="btn btn-warning" />
            </div>
        </div>
    </div>

</asp:Content>

