<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="FrontierAg.Admin.PackCharges.Default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h3>Packaging Charges List</h3>
    <p>
        <asp:HyperLink runat="server" NavigateUrl="~/Admin/PackCharges/AddPackCharge" Text="Create new" />
    </p>
    <div>
        <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
        <asp:GridView runat="server" ID="PackChargesGrid"
        ItemType="FrontierAg.Models.PackCharge" DataKeyNames="PackChargeId" AutoGenerateEditButton="true"
        SelectMethod="PackChargesGrid_GetData" UpdateMethod="PackChargesGrid_UpdateItem" CssClass="table table-striped table-bordered" EnableModelValidation="true"
        AutoGenerateColumns="false" DeleteMethod="PackChargesGrid_DeleteItem" AutoGenerateDeleteButton="true">
        <Columns>
            <asp:TemplateField HeaderText="Product No">
              <ItemTemplate>
                <asp:Label Text="<%# Item.Product.ProductNo %>"
                    runat="server" />
              </ItemTemplate>
            </asp:TemplateField>  
            <%--<asp:DynamicField DataField="PackChargeId" ReadOnly="true"/>--%>
            <asp:DynamicField DataField="From" />
            <asp:DynamicField DataField="To" />
            <asp:DynamicField DataField="PackChargeAmt" /> 
                
            <%--<asp:TemplateField HeaderText="Product Name">
              <ItemTemplate>
                <asp:Label Text="<%# Item.Product.ProductName %>" 
                    runat="server" />
              </ItemTemplate>
            </asp:TemplateField>   
               --%>           
        </Columns>
    </asp:GridView>
        <div class="row">
					  &nbsp;
					</div>
					<div class="form-group">
						<div>
							<asp:button id="backButton" runat="server" text="Back" OnClientClick="JavaScript:window.history.back(1);return false;" CssClass="btn btn-warning" />
						</div>
					</div>
    </div>
</asp:Content>
